apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
    - name: helloworld
      port: 8080
      protocol: TCP
      targetPort: 80
  